menu:
    Home: /
    Weibo: http://weibo.com/simpkae
    RSS: /atom.xml
    Github: https://github.com/simpkae

favicon: /favicon.png
logo: /favicon.png

# comment
# e.g disqus: seansun
disqus:
duoshuo:

# google-analytics:
# ga:
# baidu-analytics:
# ba: