menu:
    主頁: /
    微博: http://weibo.com/leszeu
    關於: /about

favicon: /favicon.ico
logo: /logo.png

# comment
# e.g disqus: seansun
disqus:
duoshuo:

# google-analytics:
# ga:
# baidu-analytics:
# ba:
