menu:
    主頁: /
    微博: http://weibo.com/simpkae
    訂閱: /atom.xml

favicon: /favicon.ico
logo: /logo.png

# comment
# e.g disqus: seansun
disqus:
duoshuo:

# google-analytics:
# ga:
# baidu-analytics:
# ba:
