menu:
    主页: /
    微博: http://weibo.com/simpkae
    订阅: /atom.xml
    GitHub: https://github.com/simpkae

favicon: /favicon.ico
logo: /logo.png

# comment
# e.g disqus: seansun
disqus:
duoshuo:

# google-analytics:
# ga:
# baidu-analytics:
# ba:
